# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checkov-job:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Prisma Cloud
    env:
      PRISMA_API_URL: https://api0.prismacloud.io/
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Run Prisma Cloud action
        id: Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: '.'
          soft_fail: true
          api-key: ${{ secrets.BC_API_KEY }}
      - name: Expose report
        uses: actions/upload-artifact@v3
        with:
          name: SARIF results
          path: results.sarif
      - uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif


#Azure DevOPs Actual Code you can copy and paste:
#*** Remember to use your own variable settings

name: Checkov ADO action

Trigger:
  - main
pr:
  - main
pool:
  vmImage: ubuntu-latest
variables:
  - group: BC_Variable_Group
jobs:
  - job: Scan
    pool:
      vmImage: ubuntu-latest
    displayName: Scan

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: 3.8
        displayName: “Use Python 3.8”
      - script: pip install checkov
        displayName: Install Checkov
      - script: checkov -d . --use-enforcement-rules --bc-api-key $(BC_API_KEY)  --repo-id jmagee-panw/ADODemo --branch main -o cli -o junitxml --output-file-path console,CheckovReport.xml
        workingDirectory: $(System.DefaultWorkingDirectory)
        displayName: Run Checkov scan
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: “JUnit”
          testResultsFiles: “**/CheckovReport.xml”
          testRunTitle: PrismaCloudTests
        displayName: Publish Test Results
        condition: always()
